### PR TITLE
#183 lodash dependency

### PR DESCRIPTION
**Pull request by patrickcate**

### CODE REVIEW

**Comment by patrickcate** [comment]
@glebmachine I was wondering if you had any insights into why the two cache/not cache tests might be failing?

**Comment by glebmachine** [comment]
@patrickcate hi!
I'm stop using this project by myself(

Do you want to become mantainer?

**Comment by patrickcate** [comment]
@glebmachine sure, I can help where I can.

**Comment by glebmachine** [comment]
@patrickcate  i've added you to collaborators, thank you!

Feel free to make any changes you want)

**Comment by glebmachine** [comment]
@patrickcate could
You share your npm account, I would like to add you to collaborators there

It will allows you to publish updates to npm

**Comment by patrickcate** [comment]
My npm username is: pcate

**Comment by glebmachine** [comment]
@patrickcate Done!

**Pull request merged**
